### PR TITLE
#289 - feature/ add key events to the naming model component.

### LINKED ISSUE #289: Create the request/folder with enter button in the modal
**Describe the bug**
If i type a name in the name modal. I will have the possibility to click enter button to create the request/folder. i would also like to have the option of canceling this with esc button.

Image

The modal is in src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx

### PR DESCRIPTION
**Pull request by Rammah-mohamed**
## What does this PR do?
This PR handles key events which are enter/scapce keys to create/cancel the naming process for the request or a folder for the naming model component.

fix #289 

## Description of feature
- Inserted the save and cancel buttons inside a form. It handles the Enter and Escape key events. Because the component uses 'Shadcn/ui', a modern, customizable React component library built on top of 'Radix UI' + 'Tailwind CSS. When using an HTML form the 'Radix ui' under the hood handles the keyboard interaction like enter or escape.

### CODE REVIEW

File: src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx
Comment (giemic8) [inline src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx:1]: I think we should fix this by using a form and a submit button. Perhaps you can find some information about that if you Google 'Shadcn/ui' and 'submit button.'

**Review by giemic8 — CHANGES_REQUESTED** [review]

File: src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx
Comment (Rammah-mohamed) [reply src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx:1]: Ok. I will look at it.

File: src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx [hunk 1]
```diff
@@ -55,6 +58,22 @@ export const NamingModal = ({ createType, trufosObject, isOpen, setOpen }: Namin
     setOpen(false);
   };
 
+  const handleKeyPress = (event: KeyboardEvent) => {
+    if (event.key === 'Enter' && saveRef.current) {
+      saveRef.current.click();
+    }
+    if (event.key === 'Escape' && cancleRef.current) {
```
[the remark this answers is not in the document]
Comment (Rammah-mohamed) [reply src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx:65]: I tested it.
It works with this approach.

[the remark this answers is not in the document]
Comment (giemic8) [reply src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx:65]: For me, however, escape also works without this approach. Less code is better.

[the remark this answers is not in the document]
Comment (Rammah-mohamed) [reply src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx]: Can you review the new changes?

File: src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx
Comment (Rammah-mohamed) [reply src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx:1]: Thank you for guiding me to search about 'Shadcn/ui' library.
I learned something new.

File: src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx [hunk 2]
```diff
@@ -73,27 +74,35 @@ export const NamingModal = ({ createType, trufosObject, isOpen, setOpen }: Namin
...
+          <DialogFooter className="bottom-0">
+            <Button
+              type="submit"
+              onClick={save}
+              disabled={!isValid}
+              variant={isValid ? 'default' : 'defaultDisable'}
+            >
+              <span className="leading-4 font-bold">Save</span>
+            </Button>
+            <Button onClick={() => setOpen(false)} variant="destructive">
```
Comment (giemic8) [inline src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx:101]: Add here type="reset" and `onReset={() => setOpen(false)}` to the form.

File: src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx [hunk 3]
```diff
@@ -1,4 +1,5 @@
-import React, { useEffect, useState } from 'react';
+/* eslint-disable @typescript-eslint/no-unused-vars */
```
Comment (giemic8) [inline src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx:1]: Why do we need this?

**Review by giemic8 — CHANGES_REQUESTED** [review]

**Comment by giemic8** [comment]
@Rammah-mohamed Please resolve also the merge conflict.

**Comment by Rammah-mohamed** [comment]
I will make the changes.

File: src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx [hunk 4]
```diff
@@ -73,27 +74,35 @@ export const NamingModal = ({ createType, trufosObject, isOpen, setOpen }: Namin
...
+              value={name}
+              onChange={(e) => setName(e.target.value)}
+              className="w-full bg-transparent outline-none"
+              placeholder="Enter the folder name"
+            />
+          </div>
+          <DialogFooter className="bottom-0">
+            <Button
+              type="submit"
+              onClick={save}
```
[the remark this answers is not in the document]
Comment (giemic8) [reply src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx:95]: Please check this twice I'm not sure.

[the remark this answers is not in the document]
Comment (Rammah-mohamed) [reply src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx:95]: I will

File: src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx (hunk 3 above)
Comment (Rammah-mohamed) [reply src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx:1]: This is already been in the Project.
I didn't add it.

**Comment by Rammah-mohamed** [comment]
Can you review it?

**Review by giemic8 — APPROVED** [review]
