### PR TITLE
fix: prevent creating collection without selecting directory

### LINKED ISSUE #726: [Bug] Collection is not created when no directory is selected and no validation or feedback is shown
**Describe the bug**
When creating a new collection, if no directory is selected, clicking the **Create Collection** button does not create a collection and no error message, validation feedback, or toast notification is shown. The UI appears unresponsive, which may confuse users.

**To Reproduce**

1. Go to the Trufos application.
2. Click on **Create Collection**.
3. Enter a valid collection name.
4. Do not select any directory or folder.
5. Click on **Create Collection**.
6. Observe that nothing happens and no feedback is shown.

**Expected behavior**
The application should validate the directory selection before creating a collection. If no directory is selected, it should:

* Show an error message or toast notification.
* Or disable the **Create Collection** button until a directory is selected.
* Or prompt the user to select a directory.

**Additional context**
The collection is successfully created when a valid directory is selected. This suggests that the current implementation lacks proper validation or user feedback when the directory field is empty. This may affect user experience and lead to confusion.

### PR DESCRIPTION
**Pull request by Roshan-Singh-07**
Fixes #726

Previously, the "Create Collection" button could be enabled even when no directory was selected due to incorrect validation logic.
Now the button is disabled unless both a title and a directory are provided.

### CODE REVIEW

File: src/renderer/view/CollectionCreate.tsx [hunk 1]
```diff
@@ -46,9 +46,12 @@ export const CollectionCreate: React.FC<{
   const [targetEntry, setTargetEntry] = useState<DroppedEntryInfo>();
   const [title, setTitle] = useState<string>('');
 
-  const isCreationDisabled = !title && !targetEntry?.name;
+  const isCreationDisabled = !title || !targetEntry?.path;
 
   const createCollection = async () => {
+    if (!targetEntry?.path) {
+      return;
+    }
```
Comment (SoulKa) [inline src/renderer/view/CollectionCreate.tsx]: this check is redundant since we're already having the same check in line 49 to disable the button that calls this method. So we can remove these lines. After that we're ready to merge :)

Comment (Roshan-Singh-07) [reply src/renderer/view/CollectionCreate.tsx]: Good catch, thanks! I’ve removed the redundant check.

**Review by SoulKa — APPROVED** [review]
