### PR TITLE
Align sidebar with Penpot design (#630)

### LINKED ISSUE #630: Align sidebar with penpot design
**Describe the bug**

Currently the sidebar does not look exactly like the trufos penpot design. We should make the necessary adjustments so that it looks as close to the design as possible.

Here are the major differences that we should fix:

- The text should not be white, but instead should be colored with the `secondary` color
- The font should be lato, and not calt
- The text of the `HttpMethodSelect` should have a font weight of `400`
- When hovering over the `Send` button, the `pointer` cursor should be used

**To Reproduce**

1. Start trufos and look at the main top bar
2. Compare it to the penpot design

**Expected behavior**

The implementation should look like the penpot design.

**Screenshots/Video**

Current implementation:

Image

Intended look and feel from the penpot design:

Image

**Additional context**

You can take a look at our [penpot design here](https://penpot.soulka.de/#/view?file-id=88a057e2-ffe4-81cb-8005-c2e9c63649bf&page-id=88a057e2-ffe4-81cb-8005-c2e9c63649c0&section=interactions&index=0&share-id=7dc8c998-94ea-8097-8007-0dc398111f50). You can get better access to the penpot design by clicking on [this link](https://penpot.soulka.de/#/workspace?team-id=88a057e2-ffe4-81cb-8005-bf2df0f05306&file-id=88a057e2-ffe4-81cb-8005-c2e9c63649bf&page-id=28ed7eca-9ec9-80d6-8006-a7a88572810c&layout=layers&board-id=3f28eb09-ff7d-8035-8006-a80c396f5913) and logging in with the username `info@trufos.com` and password `password`.

### PR DESCRIPTION
**Pull request by Roshan-Singh-07**
This PR aligns the sidebar with the official Penpot design to improve visual consistency and UX.

### Changes
- Updated sidebar typography to use **Lato** and secondary text color
- Set HTTP method labels to **font-weight 400**
- Made request and folder context menus (three dots) visible **only on hover**
- Fixed text truncation to prevent overlap with context menu
- Ensured consistent hover behavior between requests and folders
- Fixed a TypeScript issue where a non-renderable URL object could be passed as a React child (fallback now uses `url.base`)

### Result
- Sidebar now visually matches the Penpot design
- Cleaner UI with less visual noise
- Improved readability for long request and folder names

Demo: short screen recording attached showing hover behavior and text truncation.

https://github.com/user-attachments/assets/2e02fefb-00c1-49b3-9a32-395a6a33b4c6

Closes #630

### CODE REVIEW

**Comment by SoulKa** [comment]
This is currently blocked by #693. Will review and merge after that PR

**Comment by SoulKa** [comment]
The PR #693 is merged now. There are two conflicting changes (see `NavFolder` and `NavRequest`). You will need to rebase on the `develop` branch.

**Comment by Roshan-Singh-07** [comment]
Rebased on the latest `main` branch and resolved the conflicts in `NavFolder` and `NavRequest`.

The sidebar now preserves the recent collapsible and drag-and-drop changes while aligning the styling and behavior with the Penpot design. Please let me know if any further adjustments are needed.

Thanks!

**Comment by SoulKa** [comment]
I rebased locally, the long name cutoff is still there, the other issues seem resolved for me. So another rebase and I think the work is done

**Comment by Roshan-Singh-07** [comment]
Fixed the truncation issue for request titles and folder titles by adjusting the flex layout and ensuring the context menu does not overlap the text.
Screenshot 2026-03-12 235315
Screenshot 2026-03-12 235332

File: src/renderer/components/sidebar/SidebarRequestList/Nav/NavFolder.tsx [hunk 1]
```diff
@@ -42,40 +43,57 @@ export const NavFolder = ({ folderId, depth = 0 }: NavFolderProps) => {
...
-          'hover:bg-[#333333]',
-          getIndentation(depth)
-        )}
-        onClick={toggleFolder}
+      <Collapsible
+        asChild
+        open={isFolderOpen}
+        onOpenChange={(open) => (open ? setFolderOpen(folderId) : setFolderClose(folderId))}
+        className="group/collapsible"
       >
```
Comment (SoulKa) [inline src/renderer/components/sidebar/SidebarRequestList/Nav/NavFolder.tsx]: I think there went something wrong in the rebase. The collapsible is not needed in its current form of implementation (see line 94 where `CollapsibleContent` is empty.

You can remove the collapsible and only keep the `SidebarMenuSubButton` as it's implemented on the main branch. This PR should likely only modify CSS class names

**Comment by Roshan-Singh-07** [comment]
Removed the Collapsible implementation as suggested and kept the structure consistent with the main branch by using only SidebarMenuSubButton. Thanks

**Review by SoulKa — APPROVED** [review]
